version: "3.3"

services:
    app:
        restart: always
        build: .
        volumes: 
            - .:/app
        ports:
            - '80:8000'
        command: gunicorn serve.wsgi:application --bind 0.0.0.0:8000 --workers 3