# Generated by Django 3.0.5 on 2020-05-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200527_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cta',
            new_name='cta_label',
        ),
        migrations.AddField(
            model_name='product',
            name='cta_link',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
