# Generated by Django 3.0.5 on 2020-05-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200527_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cta_label', models.CharField(max_length=100)),
                ('cta_link', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'promotion',
            },
        ),
    ]
