# Generated by Django 3.0.5 on 2020-05-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200528_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
