# Generated by Django 3.0.5 on 2020-05-29 21:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('services', '0008_auto_20200529_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotion',
            new_name='PromotionPage',
        ),
        migrations.AlterModelOptions(
            name='promotionpage',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
    ]
