# Generated by Django 3.0.5 on 2020-05-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('services', '0009_auto_20200529_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_label', models.CharField(max_length=100)),
                ('cta_link', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('promo_type', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.DeleteModel(
            name='PromotionPage',
        ),
    ]
