# Generated by Django 3.0.5 on 2020-05-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20200529_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
