# Generated by Django 3.0.5 on 2020-05-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_promotion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
