# Generated by Django 3.0.5 on 2020-05-30 00:35

from django.db import migrations, models
import django.db.models.deletion
import flex.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
        ('services', '0012_auto_20200529_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(max_length=1000)),
                ('package_category', models.CharField(max_length=1000)),
                ('smallprint', models.CharField(max_length=1000)),
                ('editor', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('margin', wagtail.core.blocks.CharBlock(help_text='Add Custom Margin', required=False)), ('padding', wagtail.core.blocks.CharBlock(help_text='Add Custom Padding', required=False)), ('background_color', wagtail.core.blocks.CharBlock(help_text='Add Custom Background', required=False)), ('element_classes', wagtail.core.blocks.CharBlock(help_text='Add Custom Classes', required=False)), ('element_id', wagtail.core.blocks.CharBlock(help_text='Add Custom Element ID', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='add additional text', required=True))])), ('full_richtext', flex.blocks.RichtextBlock()), ('carousel', wagtail.core.blocks.StructBlock([('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=300, required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='Custom Url', required=False))])))])), ('button', wagtail.core.blocks.StructBlock([('margin', wagtail.core.blocks.CharBlock(help_text='Add Custom Margin', required=False)), ('padding', wagtail.core.blocks.CharBlock(help_text='Add Custom Padding', required=False)), ('background_color', wagtail.core.blocks.CharBlock(help_text='Add Custom Background', required=False)), ('element_classes', wagtail.core.blocks.CharBlock(help_text='Add Custom Classes', required=False)), ('element_id', wagtail.core.blocks.CharBlock(help_text='Add Custom Element ID', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(blank=True, max_length=500)), ('label', wagtail.core.blocks.CharBlock(help_text='Label', required=False))]))], blank=True, null=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
            bases=('wagtailcore.page',),
        ),
    ]
