# Generated by Django 3.0.4 on 2020-03-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flex Page', 'verbose_name_plural': 'Flex Pages'},
        ),
    ]
