# Generated by Django 3.0.5 on 2020-05-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_auto_20200522_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
