# Generated by Django 3.0.4 on 2020-03-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_auto_20200306_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
