# Generated by Django 3.0.4 on 2020-03-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('flex', '0005_carouselimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Youtube', null=True)),
                ('google', models.URLField(blank=True, help_text='google', null=True)),
                ('pinterest', models.URLField(blank=True, help_text='pinterest', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='linkedin', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
